name: Release

on:
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        shell: bash
        run: uv pip install --system -r requirements_dev.txt

      - name: Build the project
        shell: bash
        run: python -m build .

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
