name: Tests

on:
  push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13', '3.14', '3.14t', '3.15.0-alpha.1']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
          python-version: ${{ matrix.python-version }}

    - name: Set up uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true

    - name: Install dependencies
      shell: bash
      run: uv pip install --system -r requirements_dev.txt

    - name: Install the library
      shell: bash
      run: uv pip install --system .

    - name: Print all libs
      shell: bash
      run: uv pip list --system

    - name: Run tests and show the branch coverage on the command line
      shell: bash
      run: |
        pth_file="$(python -c 'import sysconfig; print(sysconfig.get_path("purelib"))')/narrowing_coverage_process_startup.pth"
        printf "import os; os.getenv('COVERAGE_PROCESS_START') and __import__('coverage').process_startup()\n" > "$pth_file"
        coverage erase
        COVERAGE_PROCESS_START="$PWD/pyproject.toml" coverage run -m pytest -n auto --cache-clear --assert=plain
        coverage combine
        coverage report -m --fail-under=100 --omit='*tests*'
        coverage xml --omit='*tests*'

    - name: Upload coverage to Coveralls
      if: runner.os == 'Linux' && matrix.python-version == '3.13'
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
      uses: coverallsapp/github-action@v2
      with:
        format: cobertura
        file: coverage.xml
        flag-name: ubuntu-python-3.13-branch
      continue-on-error: true
